// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=mocks/mock_notification_cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "DelayedNotifier/internal/domain"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationCache is a mock of NotificationCache interface.
type MockNotificationCache struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationCacheMockRecorder
	isgomock struct{}
}

// MockNotificationCacheMockRecorder is the mock recorder for MockNotificationCache.
type MockNotificationCacheMockRecorder struct {
	mock *MockNotificationCache
}

// NewMockNotificationCache creates a new mock instance.
func NewMockNotificationCache(ctrl *gomock.Controller) *MockNotificationCache {
	mock := &MockNotificationCache{ctrl: ctrl}
	mock.recorder = &MockNotificationCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationCache) EXPECT() *MockNotificationCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockNotificationCache) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationCacheMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationCache)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockNotificationCache) Get(ctx context.Context, id uuid.UUID) (*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNotificationCacheMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNotificationCache)(nil).Get), ctx, id)
}

// Set mocks base method.
func (m *MockNotificationCache) Set(ctx context.Context, n *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockNotificationCacheMockRecorder) Set(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockNotificationCache)(nil).Set), ctx, n)
}
