// Code generated by MockGen. DO NOT EDIT.
// Source: notification_repository.go
//
// Generated by this command:
//
//	mockgen -source=notification_repository.go -destination=mocks/mock_notification_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "DelayedNotifier/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockNotificationRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockNotificationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockNotificationRepository)(nil).FindByID), ctx, id)
}

// FindReadyToSend mocks base method.
func (m *MockNotificationRepository) FindReadyToSend(ctx context.Context) ([]*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReadyToSend", ctx)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindReadyToSend indicates an expected call of FindReadyToSend.
func (mr *MockNotificationRepositoryMockRecorder) FindReadyToSend(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReadyToSend", reflect.TypeOf((*MockNotificationRepository)(nil).FindReadyToSend), ctx)
}

// IncrementRetries mocks base method.
func (m *MockNotificationRepository) IncrementRetries(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetries", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetries indicates an expected call of IncrementRetries.
func (mr *MockNotificationRepositoryMockRecorder) IncrementRetries(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetries", reflect.TypeOf((*MockNotificationRepository)(nil).IncrementRetries), ctx, id)
}

// List mocks base method.
func (m *MockNotificationRepository) List(ctx context.Context, limit int) ([]*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNotificationRepositoryMockRecorder) List(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotificationRepository)(nil).List), ctx, limit)
}

// Save mocks base method.
func (m *MockNotificationRepository) Save(ctx context.Context, n *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockNotificationRepositoryMockRecorder) Save(ctx, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockNotificationRepository)(nil).Save), ctx, n)
}

// UpdateStatus mocks base method.
func (m *MockNotificationRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotificationRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateStatus), ctx, id, status)
}

// UpdateStatusWithSentAt mocks base method.
func (m *MockNotificationRepository) UpdateStatusWithSentAt(ctx context.Context, id uuid.UUID, status domain.Status, sentAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusWithSentAt", ctx, id, status, sentAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusWithSentAt indicates an expected call of UpdateStatusWithSentAt.
func (mr *MockNotificationRepositoryMockRecorder) UpdateStatusWithSentAt(ctx, id, status, sentAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusWithSentAt", reflect.TypeOf((*MockNotificationRepository)(nil).UpdateStatusWithSentAt), ctx, id, status, sentAt)
}
